site_name: Software Guide

repo_url: https://github.com/cachemoney8096/software-guide/
site_url: https://cachemoney8096.github.io/software-guide/

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Light mode
      primary: teal
      accent: green
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Dark mode
      primary: teal
      accent: green
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky

extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/FRC8096
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/cachemoney.8096/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCfNN1j3l98wIVQFIbDQHCEw
    - icon: fontawesome/brands/github
      link: https://github.com/cachemoney8096

nav:
  - 'Software':
    - 'Get Started': 'software/get-started.md'
    - 'Installing Visual Studio Code': 'software/installing-vs-code.md'